
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import TopHeader from '@/components/TopHeader'


export const metadata = {
  title: 'ShajLife | Shop the premium cloath',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <TopHeader />
        <Header />
        <main>
           {children}
        </main>
        <Footer />
        </body>
    </html>
  )
}
